// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// DATABASE_URL: prefer explicit env, else build from DB_* vars (matches src/config/env.ts)
function getDatabaseUrl(): string {
  const url = process.env["DATABASE_URL"];
  if (url) return url;
  const user = process.env["DB_USER"] ?? "";
  const password = process.env["DB_PASSWORD"] ?? "";
  const host = process.env["DB_HOST"] ?? "localhost";
  const port = process.env["DB_PORT"] ?? "5432";
  const name = process.env["DB_NAME"] ?? "";
  const creds = password ? `${user}:${password}` : user;
  return `postgresql://${creds}@${host}:${port}/${name}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
